---
output: html_document
---

# DESeq Astrocytes

## Libraries
```{r libraries}
library(DESeq2)

```

## Load data
```{r load_data}

# loading brain object 
pseudo_brain <- readRDS(file.path(data_dir,"broad_single_cell",
                        "broad.labels_pseudo_bulk_astro+immune.RDS"))
```

## Generating EM tables
```{r}
# creating a list of em tables for all cell types
em_list <- list()

for (celltype in names(pseudo_brain)){
  
  cluster_df <- as.data.frame(pseudo_brain[[celltype]])
  
  cluster_df$ID <- rownames(cluster_df)
  
  cluster_df <- cluster_df[, c("ID", setdiff(names(cluster_df), "ID"))]
  
  # add to the em_list
  em_list[[celltype]] <- cluster_df
  
}

```

## Generating SS tables 
```{r}

# creating a ss list for all cell types 
ss_list <- list()

for (celltype in names(pseudo_brain)){
  
  # get the region
  counts <- pseudo_brain[[celltype]]
  
  # generate sample level metadata
  ss <- tibble(sample = colnames(counts))
  
    # generating mouse_id column
  segments <- c(1) # mouse_id
  replacement <- paste0("\\", segments[1])
  ss$mouse_id <- gsub('^([^_]+)_([^_]+)+_([^_]+)$',
                      replacement, 
                      colnames(counts))
  
    # generating mouse_id column
  segments <- c(2) # position
  replacement <- paste0("\\", segments[1])
  ss$position <- gsub('^([^_]+)_([^_]+)+_([^_]+)$',
                      replacement, 
                      colnames(counts))
  
  # generating condition column
  segments <- c(3) # condition
  replacement <- paste0("\\", segments[1])
  ss$condition <- gsub('^([^_]+)_([^_]+)+_([^_]+)$',
                          replacement, 
                          colnames(counts))
  
  # generating sample_group column 
  ss$sample_group <- paste0(ss$position, "_", ss$condition)
  
  # print to check
  print(ss)
  
  ss_list[[celltype]] <- ss
  
}

```

## Deseq for all cell types

I do all comparisons in a loop to avoid repeating code

```{r}


# main loop
for (celltype in names(pseudo_brain)){ 
  
  # current celltype
  print(celltype)
  
  # Wrap in tryCatch to handle errors
  tryCatch({
    # base path
    base_path <- file.path(data_dir,"broad_single_cell","differential_expression", "position+condition")
    
    # out path 
    celltype_path <- file.path(base_path, celltype)
    # make dir
    if (!dir.exists(celltype_path)) {dir.create(celltype_path, recursive = TRUE)}
    
    # em 
    em <- em_list[[celltype]]
    # save the em 
    write.table(em, 
                file = file.path(celltype_path, paste0("em_", celltype, ".tsv")), 
                sep = "\t", 
                row.names = FALSE, 
                quote = FALSE)
    # ss table
    ss <- ss_list[[celltype]]
    # save the ss
    write.table(ss,
                file = file.path(celltype_path, paste0("ss_", celltype, ".tsv")),
                row.names = FALSE,
                quote = FALSE,
                sep = "\t")
    
    # # Control vs Aldara
    # GetDE_fn(em_df = em,
    #          var = celltype,
    #          suffix = "C_vs_A", 
    #          sample_sheet = ss,
    #          reference = "C", 
    #          contrast = "A", 
    #          p_threshold = 0.5, 
    #          fold_threshold = 1, 
    #          out = celltype_path )
    
  }, error = function(e) {
    # Print error message and skip to the next iteration
    message(paste("Error with region:", celltype, "-", e$message))
    # remove the created folder
    unlink(celltype_path, recursive = TRUE)
  })
}


```
