# Spatial Centroid Plots

Load the broad.labels brain obj
```{r}
obj.list <- readRDS("F:/cosmx_data/objects/broad.label_objects/2024-11-06-broad_v1.3_integrated.RDS")
```

extract the immune object 
```{r}
immune <- obj.list$Immune
```

path to save the immune spatial plots
```{r}
plots_dir <- file.path(data_dir, "fine_single_cell", "spatial_segmentation_plots", "Immune_final")

# Create the directory if it does not already exist
if (!dir.exists(plots_dir)) {dir.create(plots_dir, recursive = TRUE)}
```

create a list with all the spatial fovs names/samples from immune object
```{r}
fov_list <- names(immune@images)
```

get default colors for the dimplot
```{r}
library(scales)
cluster_n <- length(unique(immune$integrated_subclusters))
dimplot_colors <- hue_pal()(cluster_n)
```

print dimplot to check the colors
```{r}
DimPlot(immune, group.by = "integrated_subclusters")
```

test segementation plot
```{r}
fov="s1055pos_bs3"
# plot 
ImageDimPlot(immune, fov = fov,
             cols = dimplot_colors,
             boundaries = "centroids",
             group.by = "integrated_subclusters",
             flip_xy = FALSE)

```


```{r}
for (fov in fov_list){
  
  # plot 
  fov_plot <- ImageDimPlot(immune, fov = fov, 
                           cols = dimplot_colors,
                           boundaries = "segmentation",
                           split.by = "integrated_subclusters",
                           flip_xy = FALSE, 
                           border.size = 0.05)+
    ggtitle(fov) +
    theme(plot.title = element_text(size = 40, hjust = 0.5))
  
  # save the plots
  ggsave(plot = fov_plot,
         file.path(plots_dir, paste0(fov, "_centroids.png")),
         width = 20, height = 20, dpi = 600)
  
}
```
