# Pseudo-Bulk [Cell types]

## Define cell types of interest

```{r}
celltypes <- c("Astrocytes", "Immune")
```

## Defining group variables to aggregate data

```{r}

group_vars <- c("broad.labels",
                "mouse_id",
                "slice_position",
                "condition")

```

## brain object

```{r}
# Loading anterior brain object
brain <- readRDS(file.path(data_dir,"objects", "brain_objects",
                           "2025_01_22_brain_v1.7_added_mouse_id.RDS"))

```

### subsetting object to include only cell types of interest

```{r subset_ant, message=FALSE, warning=FALSE}

rest_labels <- setdiff(unique(brain$broad.labels), celltypes)
# keep cells from the regions of interest
celltypes.sub <- subset(brain, broad.labels %in% rest_labels)

```

### Pseudo Bulking

```{r}

# using custom function
pseudo_brain <- PseudoBulk_fn(obj = celltypes.sub,
                              vars = group_vars)

# save the pseudo object
saveRDS(object = pseudo_brain, 
        file = file.path(data_dir,"broad_single_cell",
                        "broad.labels_pseudo_bulk_rest.RDS"))

```
